// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID              int    `json:"id"`
	Content         string `json:"content"`
	AuthorID        int    `json:"authorID"`
	PostID          int    `json:"postID"`
	PublishedAt     int    `json:"publishedAt"`
	ParentCommentID int    `json:"parentCommentID"`
}

type Post struct {
	ID          int        `json:"id"`
	Title       string     `json:"title"`
	Content     string     `json:"content"`
	PublishedAt int        `json:"publishedAt"`
	AuthorID    int        `json:"authorID"`
	Commentable bool       `json:"commentable"`
	Comments    []*Comment `json:"comments,omitempty"`
}
